branch-defaults:
  default:
    environment: twitter-map-dev
global:
  application_name: Twitter_Heat_Map
  default_ec2_keyname: DataScraperKeys
  default_platform: 64bit Amazon Linux 2015.03 v2.0.1 running Node.js
  default_region: us-east-1
  profile: null
  sc: null
